///////////////////////////////////////////////////////////////////////////////////////////////////////////
//                      THIS FILE WAS AUTO-GENERATED BY VUENGINE IDE - DO NOT EDIT                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef LANGUAGES_H_
#define LANGUAGES_H_


//---------------------------------------------------------------------------------------------------------
//												DEFINITIONS
//---------------------------------------------------------------------------------------------------------

enum LanguageIdentifiers
{
	LNG_DE,
	LNG_EN,
	LNG_ES,
	LNG_FR,
	
};

enum LanguageStrings
{
	STR_AUTO_PAUSE_EXPLANATION,
	STR_AUTOMATIC_PAUSE,
	STR_HELLO_WORLD,
	STR_LANGUAGE_SELECT,
	STR_OFF,
	STR_ON,
	STR_PRECAUTION_SCREEN_TEXT,
	STR_TAKE_A_REST,
	
};


#endif
